version: '3.1'
services:
  drupal_cont:
    image: drupal
    ports:
      - "8080:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      #- drupal-themes:/var/www/html/themes
  postgres_cont:
    image: postgres:9.6.1-alpine
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql_pass
      - POSTGRES_USER_FILE=/run/secrets/psql_user
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - psql_user
      - psql_pass

secrets:
  psql_pass:
    external: true
  psql_user:
    file: ./psql_user.txt

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  pgdata: