version: '3'
services:
  drupal_cont:
    build:
      context: .
      dockerfile: drupal.dockerfile
    ports:
      - "8080:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      #- drupal-themes:/var/www/html/themes
  postgres_cont:
    image: postgres:9.6.1-alpine
    environment:
      - POSTGRES_PASSWORD=123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  pgdata: